# Generated by Django 4.0.6 on 2022-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_incl_tax',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
