# Generated by Django 4.0.6 on 2022-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='dimension_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
