# Generated by Django 4.0.6 on 2022-07-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_seller_id_alter_order_total_incl_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller_id',
            field=models.UUIDField(null=True),
        ),
    ]
